### PR TITLE
#150 : Add --taa-sample switch to ./manage when starting the ledger

### PR DESCRIPTION
**Pull request by jcourt562**
Add --taa-sample switch to ./manage when starting the ledger to enable use of sample_aml.json and sample_taa.json files

Resolves issue #150

Signed-off-by: John Court <jcourt@anonyome.com>

### CODE REVIEW

**Review by WadeBarnes — APPROVED** [review]
Tested.  Works great.

**Comment by WadeBarnes** [comment]
@ianco, any comments before I merge?

**Comment by andrewwhitehead** [comment]
The original idea was that sample_taa.json and sample_aml.json can just be renamed to taa.json and aml.json (and modified) to take effect

**Comment by WadeBarnes** [comment]
> The original idea was that sample_taa.json and sample_aml.json can just be renamed to taa.json and aml.json (and modified) to take effect

Exactly what's happening here.

**Review by ianco — APPROVED** [review]
Looks good to me

**Pull request merged**
