### PR TITLE
Make tailing the von-network logs on start-up optional

### PR DESCRIPTION
**Pull request by WadeBarnes**

### CODE REVIEW

**Comment by TimoGlastra** [comment]
@WadeBarnes Sorry hadn't come around to make the changes. Glad you did :).

I would benefit from making the tailing of the log in the `./manage logs` command optional.

I don't know if it is the best approach, but see: https://github.com/TimoGlastra/von-network/commit/e6461164bc1f877b592049027d23305bdcb37f95 for an example. Tailing is on by default and can be disabled with `--no-tail`. E.g. `./manage logs --no-tail`.

**Comment by WadeBarnes** [comment]
@TimoGlastra, I like the idea, but that implementation is not working for me.  The `-f` flag is always being set.  I tried:
```
./manage logs --no-tail
./manage logs -no-tail
./manage logs
```

**Comment by TimoGlastra** [comment]
What shell are you using? I've tested it on both Ubuntu and macOS.

Ubuntu: `GNU bash, version 4.4.20(1)-release (x86_64-pc-linux-gnu)`
macOS:  `GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin19)`

**Comment by WadeBarnes** [comment]
`git-bash` on Windows
```
GNU bash, version 4.4.23(1)-release (x86_64-pc-msys)
```

**Comment by TimoGlastra** [comment]
I currently don't have access to a Windows computer. Will check when I have

**Comment by TimoGlastra** [comment]
I tested the script on Windows and it is working like expected. `./manage logs` will run the log command and follow it. `./manage logs --no-tail` will run the log and not follow.

Tested on Windows 10 Pro with Docker Desktop for Windows and Bash: `GNU bash, version 4.4.23(1)-release (x86_64-pc-msys)`

I'm unclear why it is not working on your side.

**Comment by WadeBarnes** [comment]
I'll re-test

**Comment by swcurran** [comment]
It would be nice to get this released.  When I start it (linux) I don't get the logging at all and didn't find an option to turn it on. The usage information doesn't say anything about the options available to control logging and in a scan of the ./manage script couldn't see how it was being controlled.

@WadeBarnes - I would also recommend removing most of the CLI information and instead pointing the users to a markdown document.  It's a lot of information and not relevant to most VON-Network users.  I don't want to lose the info, but don't think it's needed in the usage.

**Comment by TimoGlastra** [comment]
@swcurran Is the script not working for you on linux?

The expected behaviour is:
`./manage start` - start network without logging
`./manage start --logs` - start network and trail logs
`./manage logs` - output logs and tail
`./manage logs --no-tail` - output logs without tailing

**Comment by swcurran** [comment]
That helps - I wasn't using the right options.  The last one `--no-tail` did not work:

```
./manage logs --no-tail
./manage: illegal option -- -
./manage: illegal option -- n
./manage: illegal option -- o
./manage: illegal option -- -
./manage: illegal option -- t
./manage: illegal option -- a
./manage: illegal option -- i
./manage: illegal option -- l
```

**Comment by WadeBarnes** [comment]
I figured out the issue.  @TimoGlastra had made some additional changes on his `feature/manage-start-optional-logging` branch.  Those changes have now been merged into this branch.

The functionality is now working as described.

**Comment by WadeBarnes** [comment]
@swcurran, could you give it another go and approve the PR is all is working.  I'll deal with the `indy-cli` documentation issue in a separate PR.

**Comment by TimoGlastra** [comment]
Ah silly mistake of me, hadn't noticed we were not in my PR (#87) anymore

**Pull request merged**
