### PR TITLE
Fix issue with indy_config.py

### PR DESCRIPTION
**Pull request by WadeBarnes**
- Add empty line ending back.

### CODE REVIEW

**Review by swcurran — COMMENTED** [review]
Was the issue was the blank line in the file?  It looks like the removed/added lines are identical.  What was the issue?

Weird!

**Comment by WadeBarnes** [comment]
What is/was happening is that the string `NETWORK_NAME = 'sandbox'` is appended to the end of the config file on startup.  Without the blank line the last line in the config file became `logLevel = getattr(logging, os.getenv("LOG_LEVEL", "INFO").upper())NETWORK_NAME = 'sandbox'`, which caused an error on startup.  I'm not sure exactly why this was happening inside the GHA and I don't see it locally or on the Digital Ocean servers.

**Comment by swcurran** [comment]
I'm now seeing that running locally doesn't work.  The ledger is not starting up.

Logs from one node:

```
start_indy_node Node1 0.0.0.0 9701 0.0.0.0 9702
Traceback (most recent call last):
  File "/home/indy/.pyenv/versions/3.6.13/bin/start_indy_node", line 6, in <module>
    from indy_node.utils.node_runner import run_node
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/indy_node/__init__.py", line 75, in <module>
    setup_plugins()
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/indy_node/__init__.py", line 20, in setup_plugins
    from indy_common.config_util import getConfigOnce   # noqa: E402
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/indy_common/config_util.py", line 3, in <module>
    from plenum.common.config_util import getConfig as PlenumConfig, \
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/plenum/__init__.py", line 87, in <module>
    setup_plugins()
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/plenum/__init__.py", line 50, in setup_plugins
    config = getConfigOnce()
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/plenum/common/config_util.py", line 106, in getConfigOnce
    return _getConfig(general_config_dir)
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/plenum/common/config_util.py", line 87, in _getConfig
    config.GENERAL_CONFIG_FILE))
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/plenum/common/config_util.py", line 32, in extend_with_external_config
    config = getInstalledConfig(*extender)
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/plenum/common/config_util.py", line 26, in getInstalledConfig
    spec.loader.exec_module(config)
  File "/etc/indy/indy_config.py", line 16
    logLevel = getattr(logging, os.getenv("LOG_LEVEL", "INFO").upper())NETWORK_NAME = 'sandbox'
                                                                                  ^
SyntaxError: invalid syntax
```

**Comment by WadeBarnes** [comment]
Are you sure you have the latest version?  This PR fixed that issue.  You might need to delete and restore `indy_config.py` from latest.  Perhaps the update is not getting applied when you pull since it's a whitespace change.

**Comment by swcurran** [comment]
I delete the .build version in my local AATH and it pulled the file again to try to eliminate that. It definitely did a pull on the next try -- but perhaps not a build.  I'll run it again and see if I can figure it out.

**Comment by swcurran** [comment]
It took deleting the von-network-base image. Once it rebuilt from scratch it worked.

**Pull request merged**
