### PR TITLE
Added params to point to external network/genesis file

### PR DESCRIPTION
**Pull request by ianco**

### CODE REVIEW

**Comment by ianco** [comment]
Tested against Sovrin Test Network - example parameters are in the README.

2 additional parameters are required to connect to a non-default network:

GENESIS_URL
LEDGER_SEED

See example in README

**Comment by WadeBarnes** [comment]
@ianco, I've tested this on our ledgers, and Sovrin Test Net.  Things appear to be working.  I've also PRed some updates to the scripts and documentation to you.

**Comment by WadeBarnes** [comment]
@ianco, Are we at a point were we can take the `wip` label off this and merge?  Everything seesm to be functional.

**Comment by ianco** [comment]
> @ianco, Are we at a point were we can take the `wip` label off this and merge? Everything seems to be functional.

Yes I think so!

**Pull request merged**
