### PR TITLE
Add support for changes to internal Docker networking.

### PR DESCRIPTION
**Pull request by WadeBarnes**
- Networking changes introduced in Docker 4.1.x and forward on Windows and MAC stop the direct use of the internal docker host IP returned by the `docker run --rm --net=host eclipse/che-ip` process.  On Windows and MAC `host.docker.internal` needs to be used for internal connections between containers.

Signed-off-by: Wade Barnes <wade@neoterictech.ca>

### CODE REVIEW

**Comment by swcurran** [comment]
Does this approach work on Docker previous to 4.1?  E.g. how long has `host.docker.internal` worked on Windows and Mac?

**Comment by WadeBarnes** [comment]
Yes this works on Docker previous to 4.1.  `host.docker.internal` has been available on Windows and Mac for a very long time now.

**Comment by WadeBarnes** [comment]
I did a bunch of testing and troubleshooting with Docker Engine 20.10.11 on Ubuntu and have confirmed `host.docker.internal` still does not work out of the box on Linux, so the `docker run --rm --net=host eclipse/che-ip` process is still required to get the internal address.

**Review by swcurran — APPROVED** [review]
LGTM

**Pull request merged**
