### PR TITLE
Fix cli-scripts directory permission issue on some platforms.

### PR DESCRIPTION
**Pull request by WadeBarnes**
Signed-off-by: Wade Barnes <wade.barnes@shaw.ca>

### CODE REVIEW

**Comment by WadeBarnes** [comment]
@sklump, Would you mind testing this fix to see if it resolves your issue with;

```
./scripts/manage: line 83: ./cli-scripts/export-wallet.run: Permission denied
```

A quick test would be to run a `./manage build` to rebuild the docker image and then the following;
```
./manage cli reset
```
```
./manage \
  indy-cli create-wallet \
  walletName=endorser_wallet \
  storageType=default \
  storageConfig='{}' \
  storageCredentials='{}' \
  walletSeed=endorser_00000000000000000000201
```

When prompted for a key just enter `key`.  If the `create-wallet` script runs to completion successfully you should see the following;
```
load-plugin library=libindystrgpostgres.so initializer=postgresstorage_init
Plugin has been loaded: "libindystrgpostgres.so"

wallet create endorser_wallet key storage_type=default storage_config={} storage_credentials={}
Enter value for key:

Wallet "endorser_wallet" has been created

wallet open endorser_wallet key storage_credentials={}
Enter value for key:

Wallet "endorser_wallet" has been opened

did new seed=endorser_00000000000000000000201
Did "FmzL6BwFd8rvVytMKiPvxX" has been created with "~FfowF5Jtn8RMJuDhrjdBnQ" verkey

did list
+------------------------+-------------------------+----------+
| Did                    | Verkey                  | Metadata |
+------------------------+-------------------------+----------+
| FmzL6BwFd8rvVytMKiPvxX | ~FfowF5Jtn8RMJuDhrjdBnQ | -        |
+------------------------+-------------------------+----------+

wallet close
Wallet "endorser_wallet" has been closed

wallet detach endorser_wallet
Wallet "endorser_wallet" has been detached

exit

Goodbye...
```

**Comment by swcurran** [comment]
Tried it and got the same error.  I had to manually build the image with `--no-cache` to make sure I was getting the latest, so I don't think that was an issue.

I had also tried the same steps on master and got the same error.

**Comment by sklump** [comment]
@WadeBarnes , what docker container ends up running the cli-script? von_node1_1, von_node2_1, von_node3_1, von_node4, or von_webserver1 ?

Even when I try to make it write anything anywhere, I can't find it on what I think ought to be the container?

**Comment by WadeBarnes** [comment]
@sklump, Would you be able to check the permissions inside the running container for me?

Start an `indy-cli` session (which does not attempt to write a .run file):
```
$ ./manage indy-cli
indy>
```
Once the `indy>` prompt appears open a second terminal and find the running container.
```
$ docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS               NAMES
40725d9026eb        von-network-base    "./scripts/manage in…"   8 seconds ago       Up 7 seconds                            von_client_run_cb059adaa7e6
```
Open a bash shell in the container.  The `openShell.sh` script here makes that easy; [WadeBarnes/dev-tools](https://github.com/WadeBarnes/dev-tools/tree/master/docker/scripts)

```
$ openShell.sh -c von_client_run_cb059adaa7e6

Opening a 'bash' shell to von_client_run_cb059adaa7e6 ...
```

List the directories and the permissions, specifically the `cli-scripts` folder:
```
indy@40725d9026eb:~$ ls -last
total 112
4 drwxrwxrwx 2 root root 4096 Jan  7 15:00 cli-scripts
```

Collect some user info:
```
indy@40725d9026eb:~$ whoami
indy
```
```
indy@40725d9026eb:~$ id
uid=1001(indy) gid=1001(indy) groups=1001(indy),0(root)
```

**Comment by sklump** [comment]
```
indy@649ed149f93e:~$ ls -last
total 116
...
4 drwxrwxr-x 2 1000 1000 4096 Jan  7 13:18 cli-scripts
...
```

```
indy@649ed149f93e:~$ whoami
indy
```

```
indy@649ed149f93e:~$ id
uid=1001(indy) gid=1001(indy) groups=1001(indy),0(root)
```

**Comment by WadeBarnes** [comment]
Thanks, @sklump.  That confirms the permission issue, it's inheriting the permissions from the folder it's mounting.

Two more tests:
1) Run the same tests on a container started with `openShell.sh -i von-network-base`.

2) In your working copy of `von-network` run `ls -last`, `whoami`, and `id`

**Comment by sklump** [comment]
openshell requires winpty, I just use the docker primitives to get shells, but output follows:

```
indy@8ac0acaa176c:~$ ls -last
...
4 drwsrwsrwx 1 indy indy 4096 Jan  7 13:18 cli-scripts
...
```

```
indy@8ac0acaa176c:~$ whoami
indy
```

```
indy@8ac0acaa176c:~$ id
uid=1001(indy) gid=1001(indy) groups=1001(indy),0(root)
```

**Comment by WadeBarnes** [comment]
Thanks.  Thanks for the feedback on `openshell`, I'll fix that.

**Comment by WadeBarnes** [comment]
@sklump, what are the results of the second test in https://github.com/bcgov/von-network/pull/85#issuecomment-571633384

**Comment by WadeBarnes** [comment]
The most recent commit adds the shared volume label to the mount.  @sklump, could you give this most recent change a try please.

**Comment by sklump** [comment]
Sadly, same results:
./scripts/manage: line 83: ./cli-scripts/create-wallet.run: Permission denied

**Comment by WadeBarnes** [comment]
What version of Docker are you running?

**Comment by sklump** [comment]
Docker version 19.03.5, build 633a0ea838

**Comment by darapich92** [comment]
Hello, I am running the latest version of the Von-Network but I still got the same problem like @sklump . Do you have any solutions? thank you very much!

**Pull request merged**
